[package]
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]
name = "mqtt-protocol"
version = "0.4.2"
license = "MIT/Apache-2.0"
description = "MQTT Protocol Library"
keywords = ["mqtt", "protocol"]
repository = "https://github.com/zonyitoo/mqtt-rs"
documentation = "https://docs.rs/mqtt-protocol"

[dependencies]
byteorder = "1.0"
log = "0.3"
regex = "0.2"
lazy_static = "0.2"
tokio-io = "0.1.7"
futures = "0.1.22"

[dev-dependencies]
clap = "2.23"
env_logger = "0.4"
uuid = { version = "0.4", features = ["v4"] }
time = "0.1"
tokio = "0.1.7"

[lib]
name = "mqtt"
